= Setup

== Requirements

Nextflow can be used on any POSIX compatible system (Linux, OS X, etc).
It requires Bash and
http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java
8 (or later)] to be installed.

Optional requirements:

* https://www.docker.com/[Docker] engine 1.10.x (or later) 
* https://github.com/sylabs/singularity[Singularity] 2.5.x (or later, optional)
* https://conda.io/[Conda] 4.5 (or later, optional) 
* http://www.graphviz.org/[Graphviz] (optional)
* https://aws.amazon.com/cli/ [AWS CLI] (optional)
* AWS Batch computing environment properly configured (optional)

== Launch the cloud environment

For this tutorial, we will use the https://aws.amazon.com/es/cloud9/[AWS Cloud 9] virtual environment.

To launch the environment, you just need to sign in the AWS console with the https://www.crg.eu/en/cedric_notredame[CBCRG] account and specify
your (first) name as the IAM user. Below we included the list with all the users name created:

* TBC

=== Steps to launch the AWS 9 cloud environment

1. Open this address on your browser: eu-central-1.console.aws.amazon.com/cloud9/home[https://eu-central-1.console.aws.amazon.com/cloud9/home]

2. Once you are in the AWS login page, select *IAM USER* and please fill the credentials below:

    * Account ID: *885800555707*
    * IAM user name: (your username as listed above)
    * password: provided by the organization

3. When you access the AWS Cloud main page you will find your environment listed in the home page, just click on the *Open IDE* button and 
your environment will be launched.

== Training materials download 

Once you <<Steps-to-launch-the-AWS-9-cloud-environment,launched the environment>>, download the training materials running the command below
on the terminal window that you will find at the botton of the page:

[source]
----
aws s3 sync s3://cbcrg-eu/nf-training-bovreg .
----

[WARNING]
====
Don’t miss the ending dot in the above command.
====

== Environment setup 

To complete the environment setup you just need to run the script below, which installs Java an other requirements for this tutorial.

[source]
----
source setup/all.sh
----

== Nextflow Installation

Install the latest version of Nextflow copy & pasting the following snippet in a terminal window:

[source]
----
curl https://get.nextflow.io | bash
mv nextflow ~/bin
----

Check the correct installation running the following command: 

[source]
----
nextflow info
----



